### ISSUE TITLE
Node.js12 deprecation warning

### ISSUE THREAD

**Issue by dihuynh** [notiz-dev/github-action-tutorial#4]
Hi, I get the following warning when I used this action in my workflow:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: notiz-dev/github-action-json-property
```
Please update the action so it uses the [node16 runtime](https://github.blog/changelog/2022-05-20-actions-can-now-run-in-a-node-js-16-runtime/) instead

**Comment by markmssd** [comment]
I've opened this PR: https://github.com/notiz-dev/github-action-json-property/pull/5
